[package]
authors = ["Jevan Chan <jevan.cnchan@gmail.com>"]
name = "string-utils"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.59"
serde_json = "1.0.17"
wasm-bindgen = "0.2"

[profile.release]
lto = true
